### PR TITLE
ReadTheDocs configuration

### PR DESCRIPTION
**Pull request by devmessias**
- Helios logo
- sphinx-gallery
- API

### CODE REVIEW

**Review by skoudoro — CHANGES_REQUESTED** [review]
Hi @devmessias , 

A lot of temporary files, I recommend you update your gitignore before merging

**Comment by devmessias** [comment]
> Hi @devmessias ,
> 
> A lot of temporary files, I recommend you update your gitignore before merging

Hi @skoudoro .  We have a problem.Tthose files are created by the sphinx-gallery extension. However, I couldn't run the sphinx-gallery in the readthedocs. Also I think it's not possible to use the Xvfb on readthedocs

**Comment by filipinascimento** [comment]
> Hi @devmessias ,
> 
> A lot of temporary files, I recommend you update your gitignore before merging

Hi @skoudoro , we are trying to figure out the best way to run the sphinx-gallery and send this to readthedocs. We can't do that inside their environment (no Xvfb probably), so the current approach is pre-generating it and them uploading it. @devmessias proposed to have a different repo (gh-pages) for the generated documentation. We can get the org name helios-network (so the address will be helios-network.github.org/docs or something like that) and create a github action to fill this repo with the generated data. Another option would be this a page inside fury, but it could be harder for other people to reach it. What do you think?

**Comment by skoudoro** [comment]
hi @devmessias and @filipinascimento,

you are now admin of https://github.com/fury-gl/helios-website

you can use this repo for the website

**Pull request merged**
